
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_notebook:
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.5in,top=0.25in   
---

<!-- 
## PURPOSE:  generate listing of all files in a directory
-->

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = FALSE   ) # easier to read
```


```{r library, include=FALSE		}
file  <- knitr::current_input() 
file
library(jimTools)
``` 
```{r  list, echo=FALSE, include=FALSE}
thedir = "~/code/try_things_here/rmd"
l  <- list.files(thedir, pattern="*.Rmd")
# list.files("./rmd", full.names = TRUE ,pattern="*.Rmd")
# 
# list.files("./rmd", pattern="^[0-9]*")
```


```{r begin, echo=FALSE}
l
#knitr::kable(l)
```

***

```{r knit_exit(), include = FALSE  , eval=FALSE } 
# knitr::knit_exit()
```



```{r render, eval=FALSE, include=FALSE 	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root

file  <- here("rmd", "00020_list_all_files_in_dir.Rmd")
file 
# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# in general, pdf will look nicer
rmarkdown::render(file,
                  #output_format = "html_notebook",
                  #output_format = "pdf_document",
                  output_format = "html_document",
                  output_file = "~/Downloads/print_and_delete/out")
```
