---
title: Template for .Rmd
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  comment="      ##",  error=TRUE, collapse=TRUE)
```
```{r library, include=FALSE		}
load_all()
```

```{r render, eval=FALSE	}
file <- "001_compress_files.Rmd"
file  <- basename(file)
dir="rmd"

jimTools::ren_pdf(file,dir)
jimTools::ren_github(file, dir)
```
fix_dates_times
```{r aside}

x  <- lubridate::now()
x
# extract, then rebuild
lubridate::month(x)
day(x)
week(x)
hour(x)
minute(x)
second(x)

# formatting, lubridate  stringr
prefix  <- paste(year(x),month(x, label=TRUE, abbr=TRUE ),
			stringr::str_pad(day(x), width=2, side=c("left"), pad="0"),
		hour(x),minute(x), sep="_")

```

jr_compress_dir()
```{r g}
dir <- NULL

jr_compress_dir("rmd")
jr_compress_dir("R")
```

```{r}
# To inspect tar.gz
# tar doesn't like files in quotes
tar --list -f <file>
```




```{r knit_exit()}
knitr::knit_exit()
```

***






