---
title: Template for .Rmd
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

```{r setup, include=FALSE		}
knitr::opts_chunk$set(
											echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE)
```
```{r library, include=FALSE		}
load_all()
```


dependencies?
```{r begin}
package="ggplot2"
# What does package need?
jimTools::jr_package_dependencies(package=package)


# BROKEN
# What other pkg need this one?
t  <-  jimTools::jr_package_dependencies_reverse(package=package)
t  <- tibble::as_tibble(t)
t %>% head()


# fields refers to fields in DESCRIPTION of packag
# TODO, replace lib.loc with my lib
tools::dependsOnPkgs(package,
               dependencies = c("Depends", "Imports", "LinkingTo"),
               recursive = TRUE, 
							 lib.loc = NULL,
               installed =
               utils::installed.packages(lib.loc=NULL, 
																				 fields = "Enhances"))

# try this in dt?
library(datatable)

```

```{r learn_about_options}
# list of lists
length(options()) #84

t  <- tibble::tibble(name=names(options()))
print(t, n=100)
```




```{r knit_exit()}
knitr::knit_exit()
```

***


```{r render, eval=FALSE	}
file <- "001_compress_files.Rmd"
file  <- basename(file)
dir="rmd"
jimTools::ren_pdf(file,dir)
jimTools::ren_github(x=here(dir,file))
```
