	 vim:linebreak:nowrap:nospell tw=78 fo=tqlnr foldcolumn=3 
	 
--- 
# Spaces, no Tabs
title: Template for .Rmd 
output: 
  pdf_document: 
    latex_engine: xelatex
toc: TRUE 
toc_depth:  1 
fontsize: 12pt 
geometry: margin=0.5in,top=0.25in 
---


```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE) 
```

<!--  RENDER:  see bottom -->

```{r library, include=FALSE		}
library(jimTools)
``` 


BEGIN HERE (tibble, format etc)
```{r begin}
# all
options()
```

```{r knit_exit()} 
knitr::knit_exit() 
```
```{r getOption	}
getOption("width")

# set
options("jim_param"= 25)

# get
getOption("jim_param")
```


NOT WORKING
```{r environ}
jr_set_env(key = "name", value="jim")
jr_get_env("name")

Sys.setenv("name" = "jim")
Sys.getenv("name")
```


***

```{r knit_exit2()} 
knitr::knit_exit() 
```

/newpage

```{r render, eval=FALSE	} 
file <- "/home/jim/code/jimTools/rmd/004_set_options.Rmd"

file  <- basename(file) 
dir <-"rmd"

rmarkdown::render("~/code/jimTools/rmd/004_set_options.Rmd",
									output_format="pdf_document",
									output_dir="~/Downloads/print_and_delete/",
									output_file="out.pdf")

jimTools::ren_pdf(file,dir)
jimTools::ren_github(file, dir)
```
